## 項目21：コレクションクラスからの継承よりも移譲を使うようにしよう

### 理由

* コアクラスの一部のインスタンスメソッドがサブクラスを尊重しない

```ruby
class LikeArray < Array; end
x = LikeArray.new([1, 2, 3]) #=> [1, 2, 3]
y = x.reverse #=> [3, 2, 1]
y.class #=> Array

LikeArray.new([1, 2, 3]) == [1, 2, 3] #=> true
```

### 解決方法

* 内部実装として、コレクションクラスのインスタンスを持つ（外には見せない）
* 特定のメソッドをインスタンス変数に移譲を使って転送する
  * 継承よりもはるかに細かくコントロールが可能
  * クラスにとって意味のあるコレクションクラスのインスタンスメソッドだけを利用できる
  * 移譲が正解にならないメソッドについて、独自バージョンを明示的に定義できる
  * 移譲のターゲットの dup, clone, freeze, taint, untaint メソッドも忘れずに実装する

```ruby
require 'forwardable'

class RaisingHash
  extend Forwardable
  include Enumerable
  def_delegators(:@hash, :[], :[]=, :delete, :each, :keys, :values, :length, :empty?, :has_key?)

  def initialize
    @hash = Hash.new do |hash, key|
      raise(KeyError, "invalid key '#{key}'!")
    end
  end

  def invert
    other = self.class.new
    other.replace!(@hash.invert)
    other
  end

  def initialize_copy(other)
    @hash = @hash.dup
  end

  def freeze
    @hash.freeze
    super
  end

  protected
  def replace!(hash)
    hash.default_proc = @hash.default_proc
    @hash = hash
  end
end
```

# 第4章 例外
## 項目22：raise にはただの文字列ではなくカスタム例外を渡そう

### 理由

* 例外の中には、修復できるエラーを表しているものもある
* エラーを修復するためには、起こりえる様々なエラー条件を区別できなければならない
* raise を文字列だけで呼び出すこともできる。この場合、 RuntimeError が発生する。
  * RuntimeError は何かおかしいことが起きたことを示すだけの例外であり、意味をもたない

### 解決方法

* 例外クラスを継承したカスタム例外クラスを作成する。名前は Error で終わっているべき。
* 継承するのは Exception ではなく、StandardError であるべき。
  * rescue でクラス名を省略したとき、 Exception は補足できない
* 1つのプロジェクトに複数のカスタム例外クラスがある場合は、StandardError を継承した基底例外クラスを作成する
  * カスタム例外クラスは基底例外クラスを継承する
* カスタム例外クラスを使えば、エラーの種類を一意に識別できる。
  * 結果、そのコードを使う人は、その例外を処理するか、処理しないか選べるようになる。
* raise にはクラス名ではなく、例外オブジェクトを与えることもできる。

```ruby
class CoffeeTooWeakError < StandardError; end

raise CoffeeTooWeakError, "coffee to water ratio too low"

class TemperatureError < StandardError

  attr_reader :temperature

  def initialize(temperature)
    @temperature = temperature
    super("invalid temperature: #{@temperature}")
  end

end

raise TemperatureError.new(180)
```

## 項目23：できる限りもっとも対象の狭い例外を処理するようにしよう

### 理由

* ArgumentError や LocalJumpError など、コードミスに起因するエラーが意図せず処理される
* rescue 中に例外が起こると、新しい例外が現在の例外を押しのけてしまう。
  * 失われた例外が、全例外を捕まえる rescue 節でたまたま捕まえた ArgumentError のようなものだと特にまずい

### 解決方法
* 専用の例外クラスを作成して、わかりやすい形で特定のエラーを捕まえて個別に処理する
* 例外を捕まえるときは、もっとも限定されたタイプを最初に処理する。
* StandardError のような汎用例外クラスを rescue で捕まえるのは避ける。
  * 本当に必要なのは ensure なのではないか、と考える
* 例外を処理するメソッドの中で StandardError を rescue し、元の例外を raise することで、例外が失われるのを避ける

```ruby
begin
  task.perform
rescue NetworkConnectionError => e
  # 再試行ロジック
rescue InvalidRecordError => e
  send_to_support_staff(e)
rescue => e
  service.record(e)
  raise
ensure
  # クリーンアップ処理
end

def send_to_support_staff(e)
  ...
rescue
  raise e
end
```

## 項目24: リソースはブロックと ensure で管理しよう

### 理由
* ファイルなど、リソースを開いている最中に例外が起こった場合、リソースが開放されなくなる

### 解決方法
* リソースの開放は ensure 節で記述する。正常終了した場合も例外が発生した場合も、リソースの開放を保証できる。
  * ただし、リソースを示す変数が初期化されなかった場合も考えられるので、変数の nil チェックをする。
* File::open のように、ブロックを使ってリソースを管理する方法もある。
  * ブロックが渡されたときは、ブロックを処理した時点で自動的にリソースを開放
  * ブロックが渡されないときは、明示的にリソースを開放する処理が呼ばれるまでリソースを開放しない

```ruby
begin
  file = File.open(filename, 'w')
  ...
rescue
  file.close if file
end

class Lock

  def self.acquire
    lock = new
    lock.exclusive_lock!

    if block_given?
      yield(lock)
    else
      lock
    end
  ensure
    if block_given?
      # ロックを確実に解除
      lock.unlock if lock
    end
  end

end
```

## 項目25：ensure 節は最後まで実行して抜けるように作ろう

* ensure の中で制御フローを変更してはいけない。
  * return, throw, next, break

### 理由
* ensure の中で制御フローの変更を行うと、例外が発生していた場合に、例外がすべて捨てられる。
* ensure の中で return を使うと、正常に処理が完了していたときも、 return の値で返り値が上書きされる。

```ruby
items.each do |item|
  begin
    raise TooStringError if item == 'lilac'
  ensure
    next
  end
end

def hoge
  return "a"
ensure
  return "b"
end

hoge #=> "b"
```
